require('dotenv').config();

const {
  DB_PASSWORD,
  SESSION_SECRET,
  EMAIL_ADMINISTRATOR,
  CEL_ADMINISTRATOR,
  GMAIL_FROM_SEND,
  GMAIL_PASS_APPLICATION,
  TWILIO_ACCOUNT_SID,
  TWILIO_ACCOUNT_TOKEN,
  TWILIO_NUMBER_WHATSAPP,
  TWILIO_NUMBER_SMS
} = process.env;

module.exports = {
  DB_PASSWORD,
  SESSION_SECRET,
  EMAIL_ADMINISTRATOR,
  CEL_ADMINISTRATOR,
  GMAIL_FROM_SEND,
  GMAIL_PASS_APPLICATION,
  TWILIO_ACCOUNT_SID,
  TWILIO_ACCOUNT_TOKEN,
  TWILIO_NUMBER_WHATSAPP,
  TWILIO_NUMBER_SMS
}